import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const allBlogs = api.post.getAllBlogs.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">T3</span> Stack Blog
          </h1>
          <div className="grid grid-cols-3 gap-4 sm:grid-cols-3 md:gap-8">
            {allBlogs.data?.map((blog) => (
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/en/usage/first-steps"
                target="_blank"
              >
                <h3 className="text-2xl font-bold">{blog.title}</h3>
                <div className="text-lg">{blog.description}</div>
                <span className="text-sm text-gray-400">
                  {blog.createdAt.toLocaleDateString()}
                </span>
              </Link>
            ))}
          </div>
          <div className="mt-12 text-center">
            <Link
              href="/postBlog"
              className="rounded-md bg-orange-500 px-6 py-2 font-medium text-white"
            >
              投稿する
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
